name: Static checks

on: push

jobs:
  static-checks:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3

      - name: Use pnpm
        uses: pnpm/action-setup@ebcfd6995dade4b0104ac774445cef8b3b4635b0
        with:
          version: ^8.10.5

      - name: Set up Node and cache dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm lint
      - run: pnpm check-formatting
      - run: pnpm typecheck
      - run: pnpm test
